### PR TITLE
update-virtualenv: Update virtualenv to the latest version

### PR DESCRIPTION
**Pull request by alexlatchford**
Hello!

Not entirely sure if I've done everything to upgrade virtualenv to the latest version for the plugins sake but not having the latest version of pip is really hurting the speed of our deployments at the moment because of the new caching architecture in pip 8+.

Let me know what you need from me to get this merged and I'll do my best!

Many thanks,
Alex

### CODE REVIEW

**Comment by alexlatchford** [comment]
@omansion are you still maintaining this repo?

**Comment by omansion** [comment]
Virtualenv 15.0.2 is now included in the latest release (0.23)

**Comment by cjw296** [comment]
@omansion - why does the plugin need to include its own pip and virtualenv?
- could they be taken from the Python version or specified in a similar way outside the plugin?

**Comment by omansion** [comment]
We want to minimize the requirements to be able to use the plugin. All you need is a basic Python on your System.

An interesting improvement would be to use the virtualenv installed in the Python if there is one (instead of the bundled one).

**Comment by svvitale** [comment]
Agree that the preferred behavior would be a fallback approach:

1. Use a specified virtualenv (from a user setting within Jenkins)
2. Auto-discover already installed virtualenv
3. Use bundled version

This would also result in less work for plugin maintainers since having an up-to-date bundled version would become less critical.

**Pull request closed without merging**
